# Generated by Django 4.1.5 on 2023-01-04 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="posted_data",
            new_name="posted_date",
        ),
    ]
